### ISSUE TITLE
codec issue

### ISSUE THREAD

**Issue by Ibuprofenighty** [riad-azz/audio-extract#1]
Hi there, thanks for the great proposal of the work.

When trying to convert from .mp4 to .mp3, the program pops.
'Failed : Something went wrong, 'utf-8' codec can't decode byte 0xe6 in position 59: invalid continuation byte'

Could you please fix the codec problem, thanks!

**Comment by riad-azz** [comment]
Hey there, 

Can you please provide more information about the error?

And provide information about the file you want to convert, and if possible provide the file itself.

**Comment by riad-azz** [comment]
> Hi there, thanks for the great proposal of the work.
> 
> When trying to convert from .mp4 to .mp3, the program pops. 'Failed : Something went wrong, 'utf-8' codec can't decode byte 0xe6 in position 59: invalid continuation byte'
> 
> Could you please fix the codec problem, thanks!

The library  has been refactored and updated, the problem should be fixed now.

Have a nice day.
