### ISSUE TITLE
Running with Linux

### ISSUE THREAD

**Issue by dvarkless** [riad-azz/audio-extract#2]
Hi. Thanks for the package, this is exactly that I need. Currently i'm having an issue then running it on my machine.
I wanted to extract audio:
```python
audio_path = f"./temp/temp.mp3"
extract_audio(input_path=str(file_path), output_path=audio_path)
```

The `output_path` dir exists on my system, but the library tries to create it anyways:
Traceback:
```sh
  File "/run/media/dvarkless/LinuxData/Files/PythonProjects/some_dir/venv/lib/python3.10/site-packages/audio_extract/ffmpeg.py", line 16, in extract_audio
    result = validator.validate()
  File "/run/media/dvarkless/LinuxData/Files/PythonProjects/some_dir/venv/lib/python3.10/site-packages/audio_extract/validators.py", line 31, in validate
    self._validate_output_path()
  File "/run/media/dvarkless/LinuxData/Files/PythonProjects/some_dir/venv/lib/python3.10/site-packages/audio_extract/validators.py", line 59, in _validate_output_path
    os.makedirs(folder_path)
  File "/home/dvarkless/.pyenv/versions/3.10.11/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

I noticed, that the separators in the code are in Windows style '\\':
```python
# ./audio_extract/validators.py
    def _validate_output_path(self):
        output_path = self.output_path
        if output_path.endswith("/") or output_path.endswith("\\"):
            output_path += "audio." + self.output_format

        output_path = os.path.abspath(output_path)
        output_parts = output_path.split('\\')    # Here 
        filename = output_parts[-1]
        folder_path = "\\".join(output_parts[:-1])  # And here 
     ....
```

I think it doesn't work on my linux system.

As stated in the [documentation](https://docs.python.org/3/library/os.html?highlight=os#os.sep), `os.sep` is system independent and should be used instead of explicitly typing separators.

**Comment by riad-azz** [comment]
Hey, Thanks for reporting this because i would have never foundout since i use windows. I made the change and pushed it but i can't really test it so pleaes let me know if the issue is fixed for you.

**Comment by dvarkless** [comment]
Looks like the issue with output path is gone, thanks

**Comment by dvarkless** [comment]
Now i'm having a different error :)

**Comment by dvarkless** [comment]
The command arguments seems to be wrong
```sh
  File "/run/media/dvarkless/LinuxData/Files/PythonProjects/some_dir/src/bot/action_handlers.py", line 42, in video_handler
    extract_audio(input_path=str(file_path), output_path=audio_path)
  File "/run/media/dvarkless/LinuxData/Files/PythonProjects/some_dir/venv/lib/python3.10/site-packages/audio_extract/ffmpeg.py", line 39, in extract_audio
    raise Exception(f"Failed : {error}.")
Exception: Failed : Use -h to get full help or, even better, run 'man ffmpeg'.
```
But then I run the ffmpeg itself, the same arguments seems to be work just fine:
```sh
ffmpeg -i ./Video/somevideo.MOV -ss 0 -f mp3 -y ./Video/test.mp3

...
>>> size=    1840kB time=00:01:57.70 bitrate= 128.1kbits/s speed=58.6x
>>> video:0kB audio:1840kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.018098%
```

I'll run the debuger and comment if I can figure something out

**Comment by dvarkless** [comment]
I fixed the problem by removing argument `shell=True` from the subprocess call. Now the function works fine.
```python
# ./audio_extract/ffmpeg.py
# Line 34
result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
I don't know why this works, but it works for me

**Comment by riad-azz** [comment]
I dont really remember why I had it there to begin with it might have been for debbuging.
I think on linux it needs permissions to run with `shell=True` but if it works without it then ts not needed. 
Anyway i removed it and thanks a lot once again for the feedback.
